'use strict';

const PLATFORMS = [
  {
    title: 'PlayStation',
    slug: 'playstation',
    order: 1,
    iconUrl: 'https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/playstation.svg',
  },
  {
    title: 'Nintendo',
    slug: 'nintendo',
    order: 2,
    iconUrl: 'https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/nintendo.svg',
  },
  {
    title: 'PC',
    slug: 'pc',
    order: 3,
    iconUrl: 'https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/steam.svg',
  },
  {
    title: 'Xbox',
    slug: 'xbox',
    order: 4,
    iconUrl: 'https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/xbox.svg',
  },
  {
    title: 'Sega',
    slug: 'sega',
    order: 5,
    iconUrl: 'https://cdn.jsdelivr.net/npm/simple-icons@11.14.0/icons/sega.svg',
  },
];

const GAMES = [
  // PlayStation
  {
    title: 'God of War',
    platformSlug: 'playstation',
    steamId: 1593500,
    price: 49.99,
    discount: 15,
    releaseDate: '2022-01-14',
    video: 'https://www.youtube.com/watch?v=EE-4GvjKcfs',
  },
  {
    title: 'Horizon Forbidden West',
    platformSlug: 'playstation',
    steamId: 2420110,
    price: 59.99,
    discount: 10,
    releaseDate: '2024-03-21',
    video: 'https://www.youtube.com/watch?v=LqBcNXaEArY',
  },
  {
    title: 'Ghost of Tsushima',
    platformSlug: 'playstation',
    steamId: 2215430,
    price: 59.99,
    discount: 0,
    releaseDate: '2024-05-16',
    video: 'https://www.youtube.com/watch?v=IQ1dCxcSNRM',
  },
  {
    title: 'The Last of Us Part I',
    platformSlug: 'playstation',
    steamId: 1888930,
    price: 69.99,
    discount: 20,
    releaseDate: '2023-03-28',
    video: 'https://www.youtube.com/watch?v=W2Wnvkj15Fc',
  },
  {
    title: 'Returnal',
    platformSlug: 'playstation',
    steamId: 1649240,
    price: 59.99,
    discount: 5,
    releaseDate: '2024-02-27',
    video: 'https://www.youtube.com/watch?v=OvDrX0AAH6Q',
  },

  // Xbox
  {
    title: 'Halo Infinite',
    platformSlug: 'xbox',
    steamId: 1240440,
    price: 59.99,
    discount: 0,
    releaseDate: '2021-12-08',
    video: 'https://www.youtube.com/watch?v=PyMlV5HRW0M',
  },
  {
    title: 'Forza Horizon 5',
    platformSlug: 'xbox',
    steamId: 1551360,
    price: 59.99,
    discount: 25,
    releaseDate: '2021-11-09',
    video: 'https://www.youtube.com/watch?v=FYH9n37d7EE',
  },
  {
    title: 'Starfield',
    platformSlug: 'xbox',
    steamId: 1716740,
    price: 69.99,
    discount: 15,
    releaseDate: '2023-09-06',
    video: 'https://www.youtube.com/watch?v=pBy1zgt0PMc',
  },
  {
    title: 'Gears 5',
    platformSlug: 'xbox',
    steamId: 1097840,
    price: 39.99,
    discount: 30,
    releaseDate: '2019-09-06',
    video: 'https://www.youtube.com/watch?v=I2yA1__dbs0',
  },
  {
    title: 'Sea of Thieves',
    platformSlug: 'xbox',
    steamId: 1172620,
    price: 39.99,
    discount: 10,
    releaseDate: '2018-03-20',
    video: 'https://www.youtube.com/watch?v=r5JIBaasuE8',
  },

  // PC
  {
    title: 'Cyberpunk 2077',
    platformSlug: 'pc',
    steamId: 1091500,
    price: 59.99,
    discount: 50,
    releaseDate: '2020-12-10',
    video: 'https://www.youtube.com/watch?v=LembwKDo1Dk',
  },
  {
    title: 'Elden Ring',
    platformSlug: 'pc',
    steamId: 1245620,
    price: 59.99,
    discount: 0,
    releaseDate: '2022-02-25',
    video: 'https://www.youtube.com/watch?v=E3Huy2Krs-v',
  },
  {
    title: "Baldur's Gate 3",
    platformSlug: 'pc',
    steamId: 1086940,
    price: 59.99,
    discount: 10,
    releaseDate: '2023-08-03',
    video: 'https://www.youtube.com/watch?v=1T22wNvoNiU',
  },
  {
    title: 'Counter-Strike 2',
    platformSlug: 'pc',
    steamId: 730,
    price: 0,
    discount: 0,
    releaseDate: '2023-09-27',
    video: 'https://www.youtube.com/watch?v=nSE38P0enYo',
  },
  {
    title: 'Half-Life: Alyx',
    platformSlug: 'pc',
    steamId: 546560,
    price: 59.99,
    discount: 20,
    releaseDate: '2020-03-23',
    video: 'https://www.youtube.com/watch?v=O2W0N3uKXm0',
  },

  // Nintendo (juegos multiplataforma también disponibles en Switch)
  {
    title: 'Hades',
    platformSlug: 'nintendo',
    steamId: 1145360,
    price: 24.99,
    discount: 0,
    releaseDate: '2020-09-17',
    video: 'https://www.youtube.com/watch?v=91Z9QOW9J2k',
  },
  {
    title: 'Hollow Knight',
    platformSlug: 'nintendo',
    steamId: 367520,
    price: 14.99,
    discount: 10,
    releaseDate: '2018-06-12',
    video: 'https://www.youtube.com/watch?v=UAO2urG23S4',
  },
  {
    title: 'Stardew Valley',
    platformSlug: 'nintendo',
    steamId: 413150,
    price: 14.99,
    discount: 0,
    releaseDate: '2016-02-26',
    video: 'https://www.youtube.com/watch?v=ot7uXNQskfw',
  },
  {
    title: 'Cuphead',
    platformSlug: 'nintendo',
    steamId: 268910,
    price: 19.99,
    discount: 15,
    releaseDate: '2017-09-29',
    video: 'https://www.youtube.com/watch?v=NN-9SQXoi50',
  },
  {
    title: 'Celeste',
    platformSlug: 'nintendo',
    steamId: 504230,
    price: 19.99,
    discount: 20,
    releaseDate: '2018-01-25',
    video: 'https://www.youtube.com/watch?v=io7BEFa6VjI',
  },

  // Sega
  {
    title: 'Sonic Frontiers',
    platformSlug: 'sega',
    steamId: 1237320,
    price: 59.99,
    discount: 30,
    releaseDate: '2022-11-08',
    video: 'https://www.youtube.com/watch?v=Ull3P0NIIuo',
  },
  {
    title: 'Like a Dragon: Ishin!',
    platformSlug: 'sega',
    steamId: 1809700,
    price: 49.99,
    discount: 15,
    releaseDate: '2023-02-21',
    video: 'https://www.youtube.com/watch?v=0d8f2I1sGLs',
  },
  {
    title: 'Persona 5 Royal',
    platformSlug: 'sega',
    steamId: 1687950,
    price: 59.99,
    discount: 25,
    releaseDate: '2022-10-21',
    video: 'https://www.youtube.com/watch?v=yciKz9zS1Yg',
  },
  {
    title: 'Bayonetta',
    platformSlug: 'sega',
    steamId: 460790,
    price: 19.99,
    discount: 40,
    releaseDate: '2017-04-11',
    video: 'https://www.youtube.com/watch?v=JVWtC6QSpE4',
  },
  {
    title: 'Total War: WARHAMMER III',
    platformSlug: 'sega',
    steamId: 1142710,
    price: 59.99,
    discount: 10,
    releaseDate: '2022-02-17',
    video: 'https://www.youtube.com/watch?v=1u_nLEdmvAk',
  },
];

module.exports = { PLATFORMS, GAMES };
